---
# file: roles/hostname/tasks/main.yml

- name: Set the hostname from inventory
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: Copy hosts file to the server.
  template: src=templates/hosts.j2 dest=/etc/hosts
