---
# file: minecraft.yml
- hosts: miinalaiva
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
      changed_when: False
  roles:
    - apt
    - hostname
    - finnish
    - useraccounts
    - apache2
    - email
