# file: ubuntu.yml
---

- name: Install Ruby 2.3.0 into Ubuntu Xenial.
  hosts: ubuntu
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python2.7 python-simplejson
  become: yes
  roles:
    - rvm-prerequisites
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - 'ruby-2.3.0'
      rvm1_default_ruby_version: '2.3.0'
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_user: 'ubuntu'
      rvm1_rvm_version: 'stable'
      tags: ruby

- name: Set the default gemset.
  hosts: ubuntu
  vars:
    - ruby_version: '2.3.0'
  become: yes
  roles:
    - ruby-gemset
