---
# file: roles/apt/tasks/main.yml
- name: update the apt cache if it's more than eight minutes old
  apt: update_cache=yes cache_valid_time=480

- name: upgrade all the packages to the latest
  apt: upgrade=dist

- name: Install unattended upgrades
  apt: pkg={{ item }}
  with_items:
    - unattended-upgrades
    - update-notifier

- name: Configure unattended upgrades
  file: src="files/{{ item }}" dest="/etc/apt/apt.conf.d/{{ item }}" owner=root group=root mode=0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Install repository adding requirements.
  apt: pkg={{ item }}
  with_items:
    - python-apt
    - python3-apt
