---
# roles/email/handlers/main.yml

- name: update-exim4.conf
  command: update-exim4.conf

- name: restart exim4
  service: name=exim4 state=restarted

- name: update frozen-emails crontab
  command: crontab /etc/cron.d/frozen-emails
