---
# file: roles/minecraft/tasks/main.yml

- name: Autoaccept license for Java
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java 7.
  apt: name=oracle-java7-installer state=present install_recommends=yes update_cache=yes

- name: Set Java 7 Env.
  apt: pkg=oracle-java7-set-default state=present install_recommends=yes

- name: Unarchive the game backup.
  unarchive:
    src: files/minecraft.tar.gz
    dest: /home
    creates: /home/minecraft/world/data/Mineshaft.dat

- name: Chown the backup.
  file: dest=/home/minecraft owner=minecraft group=minecraft recurse=yes

- name: Install screen.
  apt: name=screen state=present

- name: Start the gameserver at reboot.
  template: src=templates/minecraft.j2 dest=/var/spool/cron/crontabs/minecraft owner=minecraft group=crontab mode=0600
