---
# file: roles/ruby-gemset/tasks/main.yml

- name: RVM | check if the bwv gemset needs to be set default.
  become_user: ubuntu
  command: bash -lc "rvm list gemsets"
  register: gemset_needs_an_update
  changed_when: gemset_needs_an_update.stdout.find('=> ruby-{{ ruby_version }}@bwv') == -1

- name: RVM | Create and use ruby-{{ ruby_version }}@bwv.
  become_user: ubuntu
  command: bash -lc "rvm use ruby-{{ ruby_version }}@bwv --create"
  when: gemset_needs_an_update.stdout.find('=> ruby-{{ ruby_version }}@bwv') == -1

- name: RVM | Use ruby-{{ ruby_version }}@bwv gemset as default.
  become_user: ubuntu
  command: bash -lc "rvm use ruby-{{ ruby_version }}@bwv --default"
  when: gemset_needs_an_update.stdout.find('=> ruby-{{ ruby_version }}@bwv') == -1

- name: Install Bundler
  become_user: ubuntu
  command: bash -lc "gem install bundler"
